apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopspro-deployment
  labels:
    app: devopspro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopspro
  template:
    metadata:
      labels:
        app: devopspro
    spec:
      containers:
        - name: devopspro-container
          image: devopspro/image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 85

